### ISSUE TITLE
Report generation

### ISSUE THREAD

**Issue by eddiezab** [MythicMeta/Documentation#3]
I'm having an issue with report generation, an error is generated and I get no message and no report. I've tried PDF, latex, json with default and modified options. Is there a way to generate the report or extract the data from mythic-cli or a docker command?

Not sure if there's a better sub-project to assign this issue, I'll be happy to re-open in a different project.

Thanks in advance!

**Comment by its-a-feature** [comment]
Just now seeing this - if you have an issue with Mythic's report generation, you should open an issue against the Mythic project itself so it's easier to track and troubleshoot
